version: "3.9"
services:
  couchdb:
    build:
      context: ./docker/couchdb
      dockerfile: Dockerfile
#    environment:
#      - COUCHDB_USER=admin
#      - COUCHDB_PASSWORD=password
    ports:
      - "5984:5984"
    volumes:
      - ./.couchdb/data:/opt/couchdb/data
      - ./.couchdb/config:/opt/couchdb/etc/local.d
