name: Cloud-Deploy
on:
  push:
    branches: [ main ]
#    # Publish semver tags as releases.
#    tags: [ 'v*.*.*' ]


jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
      - run: go version
      - run: |
          make frontend-dep
          cd frontend
          yarn run build -- --configuration sandbox --output-path=../dist

      - name: Configure AWS credentials using delegated access
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::410145376638:role/fasten-sandbox-app-gh-frontend-deploy-role
          aws-region: us-east-1

      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 sync dist s3://fasten-sandbox-app-frontend-bucket/web
          

#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      - uses: chrnorm/deployment-action@v2
#        name: Create GitHub deployment
#        id: deployment
#        with:
#          token: '${{ github.token }}'
#          environment-url: https://lighthouse.fastenhealth.com/sandbox/
#          environment: sandbox
#          initial-status: success
        # more steps below where you run your deployment scripts inside the same action

