name: Cloud-Deploy
on:
  push:
    branches: [ main ]
#    # Publish semver tags as releases.
#    tags: [ 'v*.*.*' ]


jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
      - run: go version
      - run: |
          make frontend-test
          cd frontend
          yarn run build -- --configuration sandbox --output-path=../dist
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      - uses: chrnorm/deployment-action@v2
#        name: Create GitHub deployment
#        id: deployment
#        with:
#          token: '${{ github.token }}'
#          environment-url: https://lighthouse.fastenhealth.com/sandbox/
#          environment: sandbox
#          initial-status: success
        # more steps below where you run your deployment scripts inside the same action

